// Theme definitions for the retrowave blog
// Each theme provides CSS custom property values applied via data-theme on <html>

export interface ThemeDefinition {
  id: string;
  name: string;
  description: string;
  previewColors: [string, string, string]; // 3 colors for preview swatch
  variables: Record<string, string>;
}

export const THEME_IDS = [
  'classic-xanga',
  'emo-dark',
  'scene-kid',
  'myspace-blue',
  'y2k-cyber',
  'cottage-core',
  'grunge',
  'pastel-goth',
] as const;

export type ThemeId = (typeof THEME_IDS)[number];

export const THEMES: ThemeDefinition[] = [
  {
    id: 'classic-xanga',
    name: 'Classic Xanga',
    description: 'Pink & purple pastels',
    previewColors: ['#ffb3d9', '#d9b3ff', '#b3d9ff'],
    variables: {
      '--bg-primary': '#fff0f5',
      '--bg-secondary': '#ffffff',
      '--bg-gradient-from': '#ffe4ec',
      '--bg-gradient-via': '#f3e8ff',
      '--bg-gradient-to': '#e8f4ff',
      '--border-primary': '#ff99cc',
      '--border-accent': '#ff66b3',
      '--shadow-color': '#ffb3d9',
      '--text-title': '#ff1493',
      '--text-subtitle': '#9932cc',
      '--text-body': '#333333',
      '--text-muted': '#666666',
      '--accent-primary': '#ff1493',
      '--accent-secondary': '#9932cc',
      '--button-gradient-from': '#ff99cc',
      '--button-gradient-to': '#ff66b3',
      '--button-text': '#ffffff',
      '--title-font': "'Comic Sans MS', 'Brush Script MT', cursive",
      '--header-gradient-from': '#ffb6c1',
      '--header-gradient-via': '#dda0dd',
      '--header-gradient-to': '#add8e6',
      '--card-bg': '#ffffff',
      '--footer-bg': 'rgba(255,240,245,0.8)',
      '--selection-bg': '#ff99cc',
      '--selection-text': '#ffffff',
      '--scrollbar-track': '#fff0f5',
      '--scrollbar-thumb-from': '#ff99cc',
      '--scrollbar-thumb-to': '#cc66ff',
      '--link-color': '#ff1493',
      '--link-hover': '#9932cc',
      '--code-bg': '#fff0f8',
      '--code-border': '#ffb3d9',
      '--code-text': '#9932cc',
      '--blockquote-bg': '#fff5f8',
      '--blockquote-border': '#ff99cc',
      '--strong-color': '#ff1493',
      '--em-color': '#9932cc',
      '--modal-bg': '#ffffff',
      '--modal-border': '#ff99cc',
      '--input-bg': '#ffffff',
      '--input-border': '#ffb3d9',
      '--input-focus': '#ff1493',
    },
  },
  {
    id: 'emo-dark',
    name: 'Emo Dark',
    description: 'Black & blood red',
    previewColors: ['#0a0a0a', '#8b0000', '#1a0a14'],
    variables: {
      '--bg-primary': '#0a0a0a',
      '--bg-secondary': '#141414',
      '--bg-gradient-from': '#0a0a0a',
      '--bg-gradient-via': '#140a10',
      '--bg-gradient-to': '#0a0a14',
      '--border-primary': '#8b0000',
      '--border-accent': '#dc143c',
      '--shadow-color': '#000000',
      '--text-title': '#dc143c',
      '--text-subtitle': '#8b008b',
      '--text-body': '#d0d0d0',
      '--text-muted': '#606060',
      '--accent-primary': '#dc143c',
      '--accent-secondary': '#8b008b',
      '--button-gradient-from': '#8b0000',
      '--button-gradient-to': '#dc143c',
      '--button-text': '#ffffff',
      '--title-font': "'Georgia', 'Times New Roman', serif",
      '--header-gradient-from': '#1a0000',
      '--header-gradient-via': '#1a0a14',
      '--header-gradient-to': '#140014',
      '--card-bg': '#141414',
      '--footer-bg': 'rgba(10,10,10,0.9)',
      '--selection-bg': '#dc143c',
      '--selection-text': '#ffffff',
      '--scrollbar-track': '#0a0a0a',
      '--scrollbar-thumb-from': '#8b0000',
      '--scrollbar-thumb-to': '#dc143c',
      '--link-color': '#ff6b6b',
      '--link-hover': '#dc143c',
      '--code-bg': '#1a0a0a',
      '--code-border': '#8b0000',
      '--code-text': '#ff6b6b',
      '--blockquote-bg': '#140a0a',
      '--blockquote-border': '#8b0000',
      '--strong-color': '#dc143c',
      '--em-color': '#8b008b',
      '--modal-bg': '#141414',
      '--modal-border': '#8b0000',
      '--input-bg': '#1a1a1a',
      '--input-border': '#8b0000',
      '--input-focus': '#dc143c',
    },
  },
  {
    id: 'scene-kid',
    name: 'Scene Kid',
    description: 'Neon explosion',
    previewColors: ['#000000', '#00ff00', '#ff00ff'],
    variables: {
      '--bg-primary': '#000000',
      '--bg-secondary': '#0a0a0a',
      '--bg-gradient-from': '#000000',
      '--bg-gradient-via': '#0a000a',
      '--bg-gradient-to': '#000a0a',
      '--border-primary': '#00ff00',
      '--border-accent': '#ff00ff',
      '--shadow-color': '#00ff0040',
      '--text-title': '#00ff00',
      '--text-subtitle': '#ff00ff',
      '--text-body': '#ffffff',
      '--text-muted': '#00ff0080',
      '--accent-primary': '#00ff00',
      '--accent-secondary': '#ff00ff',
      '--button-gradient-from': '#00cc00',
      '--button-gradient-to': '#00ff00',
      '--button-text': '#000000',
      '--title-font': "'Impact', 'Arial Black', sans-serif",
      '--header-gradient-from': '#001a00',
      '--header-gradient-via': '#0a000a',
      '--header-gradient-to': '#1a001a',
      '--card-bg': '#0a0a0a',
      '--footer-bg': 'rgba(0,0,0,0.95)',
      '--selection-bg': '#00ff00',
      '--selection-text': '#000000',
      '--scrollbar-track': '#000000',
      '--scrollbar-thumb-from': '#00ff00',
      '--scrollbar-thumb-to': '#ff00ff',
      '--link-color': '#00ffff',
      '--link-hover': '#ff00ff',
      '--code-bg': '#001a00',
      '--code-border': '#00ff00',
      '--code-text': '#00ff00',
      '--blockquote-bg': '#0a000a',
      '--blockquote-border': '#ff00ff',
      '--strong-color': '#00ff00',
      '--em-color': '#ff00ff',
      '--modal-bg': '#0a0a0a',
      '--modal-border': '#00ff00',
      '--input-bg': '#0a0a0a',
      '--input-border': '#00ff00',
      '--input-focus': '#ff00ff',
    },
  },
  {
    id: 'myspace-blue',
    name: 'MySpace Blue',
    description: 'Tom would be proud',
    previewColors: ['#003366', '#0066cc', '#99ccff'],
    variables: {
      '--bg-primary': '#000033',
      '--bg-secondary': '#000044',
      '--bg-gradient-from': '#000022',
      '--bg-gradient-via': '#000033',
      '--bg-gradient-to': '#001144',
      '--border-primary': '#0066cc',
      '--border-accent': '#3399ff',
      '--shadow-color': '#000066',
      '--text-title': '#3399ff',
      '--text-subtitle': '#66ccff',
      '--text-body': '#ffffff',
      '--text-muted': '#99ccff',
      '--accent-primary': '#0066cc',
      '--accent-secondary': '#66ccff',
      '--button-gradient-from': '#0044aa',
      '--button-gradient-to': '#0066cc',
      '--button-text': '#ffffff',
      '--title-font': "'Verdana', 'Tahoma', sans-serif",
      '--header-gradient-from': '#001a4d',
      '--header-gradient-via': '#002266',
      '--header-gradient-to': '#003380',
      '--card-bg': '#001133',
      '--footer-bg': 'rgba(0,0,51,0.9)',
      '--selection-bg': '#0066cc',
      '--selection-text': '#ffffff',
      '--scrollbar-track': '#000033',
      '--scrollbar-thumb-from': '#0066cc',
      '--scrollbar-thumb-to': '#3399ff',
      '--link-color': '#66ccff',
      '--link-hover': '#99ddff',
      '--code-bg': '#001144',
      '--code-border': '#0066cc',
      '--code-text': '#66ccff',
      '--blockquote-bg': '#001144',
      '--blockquote-border': '#0066cc',
      '--strong-color': '#3399ff',
      '--em-color': '#66ccff',
      '--modal-bg': '#001133',
      '--modal-border': '#0066cc',
      '--input-bg': '#000033',
      '--input-border': '#0066cc',
      '--input-focus': '#3399ff',
    },
  },
  {
    id: 'y2k-cyber',
    name: 'Y2K Cyber',
    description: 'Metallic futurism',
    previewColors: ['#1a1a2e', '#00d4ff', '#c0c0c0'],
    variables: {
      '--bg-primary': '#0f0f1a',
      '--bg-secondary': '#1a1a2e',
      '--bg-gradient-from': '#0a0a14',
      '--bg-gradient-via': '#0f0f1f',
      '--bg-gradient-to': '#14142a',
      '--border-primary': '#00d4ff',
      '--border-accent': '#c0c0c0',
      '--shadow-color': '#00d4ff40',
      '--text-title': '#00d4ff',
      '--text-subtitle': '#c0c0c0',
      '--text-body': '#e8e8e8',
      '--text-muted': '#888899',
      '--accent-primary': '#00d4ff',
      '--accent-secondary': '#c0c0c0',
      '--button-gradient-from': '#c0c0c0',
      '--button-gradient-to': '#e0e0e0',
      '--button-text': '#0f0f1a',
      '--title-font': "'Trebuchet MS', 'Orbitron', sans-serif",
      '--header-gradient-from': '#1a1a2e',
      '--header-gradient-via': '#2a2a4e',
      '--header-gradient-to': '#1a2a3e',
      '--card-bg': '#1a1a2e',
      '--footer-bg': 'rgba(15,15,26,0.95)',
      '--selection-bg': '#00d4ff',
      '--selection-text': '#0f0f1a',
      '--scrollbar-track': '#0f0f1a',
      '--scrollbar-thumb-from': '#00d4ff',
      '--scrollbar-thumb-to': '#c0c0c0',
      '--link-color': '#00d4ff',
      '--link-hover': '#ffffff',
      '--code-bg': '#14142a',
      '--code-border': '#00d4ff',
      '--code-text': '#00d4ff',
      '--blockquote-bg': '#1a1a2e',
      '--blockquote-border': '#c0c0c0',
      '--strong-color': '#00d4ff',
      '--em-color': '#c0c0c0',
      '--modal-bg': '#1a1a2e',
      '--modal-border': '#00d4ff',
      '--input-bg': '#0f0f1a',
      '--input-border': '#00d4ff',
      '--input-focus': '#ffffff',
    },
  },
  {
    id: 'cottage-core',
    name: 'Cottage Core',
    description: 'Warm & earthy',
    previewColors: ['#f5e6d3', '#7d8c5c', '#a67c52'],
    variables: {
      '--bg-primary': '#faf3e8',
      '--bg-secondary': '#fff8f0',
      '--bg-gradient-from': '#f5e6d3',
      '--bg-gradient-via': '#faf0e0',
      '--bg-gradient-to': '#f0ebe0',
      '--border-primary': '#a67c52',
      '--border-accent': '#7d8c5c',
      '--shadow-color': '#d4c4a8',
      '--text-title': '#5c4a32',
      '--text-subtitle': '#7d8c5c',
      '--text-body': '#4a3c2a',
      '--text-muted': '#8c7a5c',
      '--accent-primary': '#7d8c5c',
      '--accent-secondary': '#a67c52',
      '--button-gradient-from': '#c4a882',
      '--button-gradient-to': '#a67c52',
      '--button-text': '#ffffff',
      '--title-font': "'Georgia', 'Palatino Linotype', serif",
      '--header-gradient-from': '#e8dcc8',
      '--header-gradient-via': '#d8ccb8',
      '--header-gradient-to': '#e0d4c0',
      '--card-bg': '#fff8f0',
      '--footer-bg': 'rgba(250,243,232,0.9)',
      '--selection-bg': '#7d8c5c',
      '--selection-text': '#ffffff',
      '--scrollbar-track': '#faf3e8',
      '--scrollbar-thumb-from': '#a67c52',
      '--scrollbar-thumb-to': '#7d8c5c',
      '--link-color': '#7d8c5c',
      '--link-hover': '#5c4a32',
      '--code-bg': '#f5ebe0',
      '--code-border': '#d4c4a8',
      '--code-text': '#5c4a32',
      '--blockquote-bg': '#f5ebe0',
      '--blockquote-border': '#7d8c5c',
      '--strong-color': '#5c4a32',
      '--em-color': '#7d8c5c',
      '--modal-bg': '#fff8f0',
      '--modal-border': '#a67c52',
      '--input-bg': '#ffffff',
      '--input-border': '#d4c4a8',
      '--input-focus': '#7d8c5c',
    },
  },
  {
    id: 'grunge',
    name: 'Grunge',
    description: 'Dirty & distressed',
    previewColors: ['#1a1814', '#4a4238', '#8b7355'],
    variables: {
      '--bg-primary': '#1a1814',
      '--bg-secondary': '#242018',
      '--bg-gradient-from': '#141210',
      '--bg-gradient-via': '#1a1814',
      '--bg-gradient-to': '#1e1a16',
      '--border-primary': '#4a4238',
      '--border-accent': '#8b7355',
      '--shadow-color': '#000000',
      '--text-title': '#c9a86c',
      '--text-subtitle': '#8b7355',
      '--text-body': '#b8a888',
      '--text-muted': '#6a5a48',
      '--accent-primary': '#8b7355',
      '--accent-secondary': '#c9a86c',
      '--button-gradient-from': '#4a4238',
      '--button-gradient-to': '#5a5248',
      '--button-text': '#c9a86c',
      '--title-font': "'Courier New', 'Courier', monospace",
      '--header-gradient-from': '#2a2620',
      '--header-gradient-via': '#343028',
      '--header-gradient-to': '#2e2a24',
      '--card-bg': '#242018',
      '--footer-bg': 'rgba(26,24,20,0.95)',
      '--selection-bg': '#8b7355',
      '--selection-text': '#1a1814',
      '--scrollbar-track': '#1a1814',
      '--scrollbar-thumb-from': '#4a4238',
      '--scrollbar-thumb-to': '#8b7355',
      '--link-color': '#c9a86c',
      '--link-hover': '#dab87c',
      '--code-bg': '#1e1a16',
      '--code-border': '#4a4238',
      '--code-text': '#c9a86c',
      '--blockquote-bg': '#1e1a16',
      '--blockquote-border': '#8b7355',
      '--strong-color': '#c9a86c',
      '--em-color': '#8b7355',
      '--modal-bg': '#242018',
      '--modal-border': '#4a4238',
      '--input-bg': '#1a1814',
      '--input-border': '#4a4238',
      '--input-focus': '#c9a86c',
    },
  },
  {
    id: 'pastel-goth',
    name: 'Pastel Goth',
    description: 'Dark meets cute',
    previewColors: ['#1a1020', '#b388dd', '#ff88b4'],
    variables: {
      '--bg-primary': '#1a1020',
      '--bg-secondary': '#241830',
      '--bg-gradient-from': '#140a1a',
      '--bg-gradient-via': '#1a1024',
      '--bg-gradient-to': '#1e142a',
      '--border-primary': '#b388dd',
      '--border-accent': '#ff88b4',
      '--shadow-color': '#b388dd30',
      '--text-title': '#e0a0ff',
      '--text-subtitle': '#ff88b4',
      '--text-body': '#e0d0e8',
      '--text-muted': '#9080a0',
      '--accent-primary': '#b388dd',
      '--accent-secondary': '#ff88b4',
      '--button-gradient-from': '#9060c0',
      '--button-gradient-to': '#b388dd',
      '--button-text': '#ffffff',
      '--title-font': "'Georgia', 'Palatino', serif",
      '--header-gradient-from': '#2a1838',
      '--header-gradient-via': '#341844',
      '--header-gradient-to': '#2e1840',
      '--card-bg': '#241830',
      '--footer-bg': 'rgba(26,16,32,0.95)',
      '--selection-bg': '#b388dd',
      '--selection-text': '#1a1020',
      '--scrollbar-track': '#1a1020',
      '--scrollbar-thumb-from': '#b388dd',
      '--scrollbar-thumb-to': '#ff88b4',
      '--link-color': '#e0a0ff',
      '--link-hover': '#ff88b4',
      '--code-bg': '#1e142a',
      '--code-border': '#9060c0',
      '--code-text': '#e0a0ff',
      '--blockquote-bg': '#1e142a',
      '--blockquote-border': '#b388dd',
      '--strong-color': '#e0a0ff',
      '--em-color': '#ff88b4',
      '--modal-bg': '#241830',
      '--modal-border': '#b388dd',
      '--input-bg': '#1a1020',
      '--input-border': '#b388dd',
      '--input-focus': '#ff88b4',
    },
  },
];

export const DEFAULT_THEME: ThemeId = 'classic-xanga';

export function getTheme(id: string): ThemeDefinition {
  return THEMES.find((t) => t.id === id) ?? THEMES[0]!;
}

export function applyTheme(themeId: string): void {
  const theme = getTheme(themeId);
  const root = document.documentElement;
  root.setAttribute('data-theme', theme.id);
  for (const [key, value] of Object.entries(theme.variables)) {
    root.style.setProperty(key, value);
  }
}
